name: DDPM
type: diffusion_conditionnelle
model_dir: DDPM
train: python DDPM/train.py --batch-size 1 --max-train-samples 128 --num-workers 0 --device cpu
predict: python DDPM/predict.py --to-predict to_predict/to_predict_t2m.nc
checkpoints_dir: DDPM/checkpoints
predictions_dir: DDPM/predictions

